// Product catalog for the "Create Order" screen's product picker.
//
// The current backend has no Product model — orders just carry a raw
// items array. Rather than block product management on a backend change,
// the catalog lives here in localStorage (same pattern as assignments.js)
// so picking a product with its image/price when creating an order works
// today. See backend-reference/ (or the standalone backend project) if
// you'd rather move this server-side and share it across devices/browsers.

import { logAction } from "./auditLog.js";

const KEY = "bdmart_products";
const ADJUSTMENTS_KEY = "bdmart_stock_adjustments";

const SEED = [
  {
    id: "p-1",
    name: "Sample Product",
    price: 990,
    costPrice: 600,
    image: "",
    sku: "",
    barcode: "",
    category: "",
    supplier: "",
    tenantId: "t-main",
    stock: 50,
  },
];

const readAll = () => {
  try {
    const stored = JSON.parse(localStorage.getItem(KEY));
    return Array.isArray(stored) ? stored : SEED;
  } catch {
    return SEED;
  }
};

const writeAll = (list) => localStorage.setItem(KEY, JSON.stringify(list));

export const getProducts = () => readAll();

export const getProductById = (id) => readAll().find((p) => p.id === id) || null;

// Simple, dependency-free barcode value generator (not a real symbology
// encoder — the barcode IMAGE is generated by an external API in
// BarcodeImage.jsx using this value as the payload, same pattern as the
// QR codes already used on labels/invoices).
export const generateBarcode = () =>
  `BD${Date.now().toString().slice(-9)}`;

export const saveProduct = (product) => {
  const list = readAll();
  if (product.id) {
    const idx = list.findIndex((p) => p.id === product.id);
    if (idx >= 0) {
      list[idx] = { ...list[idx], ...product };
      writeAll(list);
      return list[idx];
    }
  }
  const created = {
    ...product,
    id: `p-${Date.now()}`,
    barcode: product.barcode || generateBarcode(),
  };
  writeAll([created, ...list]);
  return created;
};

export const deleteProduct = (id) => {
  writeAll(readAll().filter((p) => p.id !== id));
};

// Called when an order is placed with this product, to keep an
// approximate stock count. Not authoritative across multiple devices —
// flagged as a soft/local counter, good enough for a single-admin-PC setup.
export const decrementStock = (id, qty) => {
  const list = readAll();
  const idx = list.findIndex((p) => p.id === id);
  if (idx >= 0 && typeof list[idx].stock === "number") {
    list[idx].stock = Math.max(0, list[idx].stock - qty);
    writeAll(list);
  }
};

// Manual stock adjustment (restock, damage, correction) — always logged
// with a reason and the admin who made it, both in a dedicated
// adjustments list (shown on the Products page) and in the global audit
// log (see api/auditLog.js).
const readAdjustments = () => {
  try {
    const stored = JSON.parse(localStorage.getItem(ADJUSTMENTS_KEY));
    return Array.isArray(stored) ? stored : [];
  } catch {
    return [];
  }
};

const writeAdjustments = (list) =>
  localStorage.setItem(ADJUSTMENTS_KEY, JSON.stringify(list.slice(-500)));

export const adjustStock = (productId, delta, reason, adminId) => {
  const list = readAll();
  const idx = list.findIndex((p) => p.id === productId);
  if (idx < 0) return null;
  const before = list[idx].stock || 0;
  list[idx].stock = Math.max(0, before + delta);
  writeAll(list);

  const adjustments = readAdjustments();
  adjustments.push({
    id: `adj-${Date.now()}`,
    productId,
    productName: list[idx].name,
    delta,
    before,
    after: list[idx].stock,
    reason,
    adminId,
    at: new Date().toISOString(),
  });
  writeAdjustments(adjustments);

  logAction(
    null,
    adminId,
    delta > 0 ? "stock added" : "stock removed",
    `${list[idx].name}: ${before} → ${list[idx].stock} (${reason})`
  );

  return list[idx];
};

export const getStockAdjustments = (productId) =>
  readAdjustments()
    .filter((a) => !productId || a.productId === productId)
    .reverse();
